package com.dhu.ats.mapper;

import com.dhu.ats.model.Organization;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    Organization selectByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Organization record);


//    public List<Organization> getAllOrganization();

    List<Organization> getOrganizationByLayer(int layer);

    List<Organization> getOrganizationByLayerAndParentCondition(@Param("layer") int layer,@Param("parentLeft") int parentLeft,@Param("parentRight") int parentRight);
}