package com.dhu.ats.model;

import java.util.Date;

public class FixedAsset {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_asset.asset_id
     *
     * @mbg.generated
     */
    private Integer assetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_asset.asset_name
     *
     * @mbg.generated
     */
    private String assetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_asset.place_location
     *
     * @mbg.generated
     */
    private String placeLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_asset.assign_date
     *
     * @mbg.generated
     */
    private Date assignDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_asset.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_asset.asset_model
     *
     * @mbg.generated
     */
    private String assetModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixed_asset.org_id
     *
     * @mbg.generated
     */
    private Integer orgId;

    private Integer smallClassId;


    public Integer getSmallClassId() {
        return smallClassId;
    }

    public void setSmallClassId(Integer smallClassId) {
        this.smallClassId = smallClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_asset.asset_id
     *
     * @return the value of fixed_asset.asset_id
     *
     * @mbg.generated
     */
    public Integer getAssetId() {
        return assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_asset.asset_id
     *
     * @param assetId the value for fixed_asset.asset_id
     *
     * @mbg.generated
     */
    public void setAssetId(Integer assetId) {
        this.assetId = assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_asset.asset_name
     *
     * @return the value of fixed_asset.asset_name
     *
     * @mbg.generated
     */
    public String getAssetName() {
        return assetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_asset.asset_name
     *
     * @param assetName the value for fixed_asset.asset_name
     *
     * @mbg.generated
     */
    public void setAssetName(String assetName) {
        this.assetName = assetName == null ? null : assetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_asset.place_location
     *
     * @return the value of fixed_asset.place_location
     *
     * @mbg.generated
     */
    public String getPlaceLocation() {
        return placeLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_asset.place_location
     *
     * @param placeLocation the value for fixed_asset.place_location
     *
     * @mbg.generated
     */
    public void setPlaceLocation(String placeLocation) {
        this.placeLocation = placeLocation == null ? null : placeLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_asset.assign_date
     *
     * @return the value of fixed_asset.assign_date
     *
     * @mbg.generated
     */
    public Date getAssignDate() {
        return assignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_asset.assign_date
     *
     * @param assignDate the value for fixed_asset.assign_date
     *
     * @mbg.generated
     */
    public void setAssignDate(Date assignDate) {
        this.assignDate = assignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_asset.state
     *
     * @return the value of fixed_asset.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_asset.state
     *
     * @param state the value for fixed_asset.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_asset.asset_model
     *
     * @return the value of fixed_asset.asset_model
     *
     * @mbg.generated
     */
    public String getAssetModel() {
        return assetModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_asset.asset_model
     *
     * @param assetModel the value for fixed_asset.asset_model
     *
     * @mbg.generated
     */
    public void setAssetModel(String assetModel) {
        this.assetModel = assetModel == null ? null : assetModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixed_asset.org_id
     *
     * @return the value of fixed_asset.org_id
     *
     * @mbg.generated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixed_asset.org_id
     *
     * @param orgId the value for fixed_asset.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
}