package com.dhu.ats.model;

import java.util.List;

public class LargeClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column large_class.large_class_id
     *
     * @mbg.generated
     */
    private Integer largeClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column large_class.large_class_name
     *
     * @mbg.generated
     */
    private String largeClassName;

    private List<SmallClass> smallClasses;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column large_class.large_class_id
     *
     * @return the value of large_class.large_class_id
     *
     * @mbg.generated
     */
    public Integer getLargeClassId() {
        return largeClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column large_class.large_class_id
     *
     * @param largeClassId the value for large_class.large_class_id
     *
     * @mbg.generated
     */
    public void setLargeClassId(Integer largeClassId) {
        this.largeClassId = largeClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column large_class.large_class_name
     *
     * @return the value of large_class.large_class_name
     *
     * @mbg.generated
     */
    public String getLargeClassName() {
        return largeClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column large_class.large_class_name
     *
     * @param largeClassName the value for large_class.large_class_name
     *
     * @mbg.generated
     */
    public void setLargeClassName(String largeClassName) {
        this.largeClassName = largeClassName == null ? null : largeClassName.trim();
    }

    public List<SmallClass> getSmallClasses() {
        return smallClasses;
    }

    public void setSmallClasses(List<SmallClass> smallClasses) {
        this.smallClasses = smallClasses;
    }
}