package com.dhu.ats.model;

public class SmallClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_class.small_class_id
     *
     * @mbg.generated
     */
    private Integer smallClassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_class.small_class_name
     *
     * @mbg.generated
     */
    private String smallClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column small_class.large_class_id
     *
     * @mbg.generated
     */
    private Integer largeClassId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_class.small_class_id
     *
     * @return the value of small_class.small_class_id
     *
     * @mbg.generated
     */
    public Integer getSmallClassId() {
        return smallClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_class.small_class_id
     *
     * @param smallClassId the value for small_class.small_class_id
     *
     * @mbg.generated
     */
    public void setSmallClassId(Integer smallClassId) {
        this.smallClassId = smallClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_class.small_class_name
     *
     * @return the value of small_class.small_class_name
     *
     * @mbg.generated
     */
    public String getSmallClassName() {
        return smallClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_class.small_class_name
     *
     * @param smallClassName the value for small_class.small_class_name
     *
     * @mbg.generated
     */
    public void setSmallClassName(String smallClassName) {
        this.smallClassName = smallClassName == null ? null : smallClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column small_class.large_class_id
     *
     * @return the value of small_class.large_class_id
     *
     * @mbg.generated
     */
    public Integer getLargeClassId() {
        return largeClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column small_class.large_class_id
     *
     * @param largeClassId the value for small_class.large_class_id
     *
     * @mbg.generated
     */
    public void setLargeClassId(Integer largeClassId) {
        this.largeClassId = largeClassId;
    }
}